---
title: "03_eda"
author: "Julian Morales"
date: "2026-10-08"
output: html_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
data("weather_df")

weather_df = 
  weather_df |>
  mutate(
    month = lubridate::floor_date(date, unit = "month"))
```

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) + 
  geom_histogram()

#differntiating by shape
weather_df |> 
  filter(tmax >= 20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) + 
  geom_point(alpha = .75)
```

Group by

```{r}
weather_df |>
  group_by(name, month)
```

COunting things
```{r}
weather_df |>
  group_by(month) |>
  summarize(n_obs = n())

#group more than one variable too
weather_df |>
  group_by(name, month) |>
  summarize(n_obs = n())

#counting
weather_df |>
  count(month, name = "n_obs")

# Using group by and summarize even more useful
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```

```{r}
#group by and summarize with pivoting
weather_df |> 
  group_by(name, month) |> 
  summarise(
    mean_tmax = mean(tmax, na.rm= TRUE)
  ) |> 
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```

What about looking at this
```{r}
#group by and summarize with pivoting
weather_df |> 
  group_by(name, month) |> 
  summarise(
    mean_tmax = mean(tmax, na.rm= TRUE)
  ) |>
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  )|> 
  ggplot(aes(x = month, y = mean_tmax, color = name))+
  geom_point()
```


```{r}
weather_df |> 
  mutate(center_tmax = tmax - mean(tmax, na.rm = TRUE)) |> 
  ggplot(aes(x = date, y = center_tmax, color = name))+
  geom_point()

#grouping an mutating
weather_df |> 
  group_by(name)
  mutate(center_tmax = tmax - mean(tmax, na.rm = TRUE)) |> 
  ggplot(aes(x = date, y = center_tmax, color = name))+
  geom_point()
```

Try to rank things
```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(temp_rank = min_rank(desc(tmax))) |> 
  filter(temp_rank < 2)
```

lead and lag

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    lagged_tmax = lag(tmax)
  )

#multiple time scale lag
weather_df |> 
  group_by(name) |> 
  mutate(
    lagged_tmax = lag(tmax, 3),
    lead_tmax = lead(tmax)
  )
```

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    lagged_tmax = lag(tmax, 3),
    temp_change = tmax - lagged_tmax
  ) |> 
  summarize(
    sd_temp_change = sd(temp_change, na.rm = TRUE),
    mean_temp_change = mean(temp_change, na.rm = TRUE)
  )
```

import, clean, tidy, etc the pulse data, and compute mean and median BDI score at each visit

```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    values_to = "bdi"
  ) |> 
  select(id, visit, everything()) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )

pulse_df |> 
  group_by(visit) |> 
  summarize(
    mean_bdi = mean(bdi, na.rm = TRUE),
    median_bdi = median(bdi, na.rm = TRUE)
  ) |> 
  knitr::kable(digits = 2)
```


In the FAS data comupte mean outcome (ears only) across dose and day of treatment; show in a reader freidnly table

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv", skip = 3, na = c("", ".", "NA")) |> 
  janitor::clean_names()

litters_df = 
  read_csv("data/FAS_litters.csv", na = c("", ".", "NA")) |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day of tx"),3)

fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") |> 
  select(litter_number, dose, day_of_tx, everything()) |> 
  drop_na(dose, day_of_tx)

fas_df = 
  group_by(dose, day_of_tx) |> 
  pivot_longer()

  
```

